name: IPTV-Go

on:
  push:
    branches: ["main"]
    paths:
      - '**.go'    
  pull_request:
    branches: ["main"]
    paths:
      - '**.go'

jobs:
  linux_amd64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cross Compile
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: 13.2
          prepare: |
            pkg install -y node wget curl git go121 gcc bash gawk gsed
            ln -s /usr/local/bin/go121 /usr/local/bin/go
          run: |
            cd ./Golang
            GOOS=linux GOARCH=amd64 go build -o allinone_linux_amd64
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: allinone_linux_amd64
          path: Golang/allinone_linux_amd64
